#!/usr/bin/env python3
"""Regenerate include/default_templates.hpp from gitignore.io.

Fetches the gitignore content for every template the iggen detector can
produce (plus the default OS/editor templates) and embeds them as C++ raw
string literals so the tool works offline even if gitignore.io is down.

Usage:
    python3 tools/fetch_defaults.py [--output include/default_templates.hpp]
"""

import argparse
import datetime
import sys
import time
import urllib.error
import urllib.request

API = "https://www.toptal.com/developers/gitignore/api/"

# Templates reachable via detector.hpp extension_map() plus the default
# OS/editor templates added in main.cpp. Keep in sync with those sources.
TEMPLATES = [
    "c++", "c", "rust", "go", "java", "kotlin", "scala", "python", "node",
    "react", "vuejs", "csharp", "fsharp", "swift", "ruby", "php", "dart",
    "lua", "r", "julia", "elixir", "erlang", "haskell", "clojure", "cmake",
    "terraform", "linux", "macos", "windows", "visualstudiocode",
]

DELIM = "IGGEN"  # raw-string delimiter; content must not contain )IGGEN"


def fetch(name: str, retries: int = 4) -> str:
    req = urllib.request.Request(API + name, headers={"User-Agent": "iggen"})
    last = None
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                if resp.status != 200:
                    raise RuntimeError(f"{name}: HTTP {resp.status}")
                return resp.read().decode("utf-8")
        except (urllib.error.HTTPError, urllib.error.URLError, RuntimeError) as e:
            last = e
            time.sleep(1.0 * (attempt + 1))
    raise RuntimeError(f"{name}: giving up after {retries} attempts: {last}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="include/default_templates.hpp")
    args = parser.parse_args()

    version = datetime.date.today().isoformat()
    entries = []
    skipped = []
    for name in TEMPLATES:
        try:
            body = fetch(name)
        except RuntimeError as e:
            skipped.append(name)
            print(f"WARN: skipping {name}: {e}", file=sys.stderr)
            continue
        if f"){DELIM}\"" in body:
            raise RuntimeError(f"{name}: content contains raw-string delimiter")
        entries.append(f'        {{"{name}", R"{DELIM}(\n{body}\n){DELIM}"}}')

    header = f"""#pragma once

// AUTO-GENERATED by tools/fetch_defaults.py -- do not edit by hand.
// Regenerate with: python3 tools/fetch_defaults.py
#include <map>
#include <string>

namespace iggen {{

inline constexpr const char* DEFAULT_TEMPLATES_VERSION = "{version}";

inline auto default_templates() -> const std::map<std::string, std::string>& {{
    static const std::map<std::string, std::string> m = {{
{",\n".join(entries)}
    }};
    return m;
}}

}} // namespace iggen
"""
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"Wrote {args.output} with {len(entries)} templates (version {version})")
    if skipped:
        print(f"Skipped {len(skipped)} templates: {', '.join(skipped)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
